server.port=8084

aios.insumos.dir=./insumos_ejemplo
aios.plantilla-dir=./plantillas
aios.salidas-referencia-dir=./salidas_referencia

spring.datasource.url=jdbc:h2:mem:aios;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

logging.level.root=INFO
logging.level.AIOS_CELDAS=INFO
