server.port=${AIOS_PORT:8084}
server.address=${AIOS_BIND_ADDRESS:0.0.0.0}
aios.insumos-dir=${AIOS_INSUMOS_DIR}
aios.plantilla-dir=${AIOS_PLANTILLA_DIR:./plantillas}
aios.salidas-referencia-dir=${AIOS_REFERENCIAS_DIR:./salidas_referencia}
aios.macro-recalc-491-493=false
aios.datasource.url=${AIOS_DB_URL:jdbc:teradata://10.40.176.8/DATABASE=prod_dwh_consulta,LOGMECH=LDAP}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
